<html>
<head>
<title>
sv&e - Sistema de Votaciones & Encuestas 
</title>
<link rel="stylesheet" href="./includes/estilo.css" type="text/css">
<script language="JavaScript" src="./includes/funciones.js"></script>
</head>
<body>
<table border=0 width=100% cellpadding=5 cellspacing=0>
	<tr>
		<td align=center valign=middle class=grande>
	sv&e
		</td>
	</tr>
	<tr>
		<td align=center valign=middle class="tipoGRIS">
	Sistema de Votaciones & Encuestas
		</td>
	</tr>
</table>
<hr noshade size="1">
<center>